package pyro;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-10-29T18:03:20.472+01:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebService(targetNamespace = "http://pyro/", name = "TemperatureService")
@XmlSeeAlso({ObjectFactory.class})
public interface TemperatureService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://pyro/", className = "pyro.GetDescription")
    @WebMethod
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://pyro/", className = "pyro.GetDescriptionResponse")
    public java.lang.String getDescription();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getConfigurationAssistURI", targetNamespace = "http://pyro/", className = "pyro.GetConfigurationAssistURI")
    @WebMethod
    @ResponseWrapper(localName = "getConfigurationAssistURIResponse", targetNamespace = "http://pyro/", className = "pyro.GetConfigurationAssistURIResponse")
    public java.lang.String getConfigurationAssistURI();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isActive", targetNamespace = "http://pyro/", className = "pyro.IsActive")
    @WebMethod
    @ResponseWrapper(localName = "isActiveResponse", targetNamespace = "http://pyro/", className = "pyro.IsActiveResponse")
    public java.lang.Boolean isActive();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUuid", targetNamespace = "http://pyro/", className = "pyro.GetUuid")
    @WebMethod
    @ResponseWrapper(localName = "getUuidResponse", targetNamespace = "http://pyro/", className = "pyro.GetUuidResponse")
    public java.lang.String getUuid();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCommonName", targetNamespace = "http://pyro/", className = "pyro.GetCommonName")
    @WebMethod
    @ResponseWrapper(localName = "getCommonNameResponse", targetNamespace = "http://pyro/", className = "pyro.GetCommonNameResponse")
    public java.lang.String getCommonName();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpecificationURI", targetNamespace = "http://pyro/", className = "pyro.GetSpecificationURI")
    @WebMethod
    @ResponseWrapper(localName = "getSpecificationURIResponse", targetNamespace = "http://pyro/", className = "pyro.GetSpecificationURIResponse")
    public java.lang.String getSpecificationURI();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEndpointURI", targetNamespace = "http://pyro/", className = "pyro.GetEndpointURI")
    @WebMethod
    @ResponseWrapper(localName = "getEndpointURIResponse", targetNamespace = "http://pyro/", className = "pyro.GetEndpointURIResponse")
    public java.lang.String getEndpointURI();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTemp", targetNamespace = "http://pyro/", className = "pyro.GetTemp")
    @WebMethod
    @ResponseWrapper(localName = "getTempResponse", targetNamespace = "http://pyro/", className = "pyro.GetTempResponse")
    public java.lang.Integer getTemp();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://pyro/", className = "pyro.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://pyro/", className = "pyro.GetVersionResponse")
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://pyro/", className = "pyro.GetStatus")
    @WebMethod
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://pyro/", className = "pyro.GetStatusResponse")
    public java.lang.String getStatus();
}
