package pyro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-10-29T18:03:20.472+01:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebServiceClient(name = "TemperatureServiceService", 
                  wsdlLocation = "file:/C:/dev/servicemix/data/pax-web-jsp/external_PyroService.wsdl",
                  targetNamespace = "http://pyro/") 
public class TemperatureServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pyro/", "TemperatureServiceService");
    public final static QName TemperatureServicePort = new QName("http://pyro/", "TemperatureServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/dev/servicemix/data/pax-web-jsp/external_PyroService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TemperatureServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/dev/servicemix/data/pax-web-jsp/external_PyroService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TemperatureServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TemperatureServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TemperatureServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TemperatureService
     */
    @WebEndpoint(name = "TemperatureServicePort")
    public TemperatureService getTemperatureServicePort() {
        return super.getPort(TemperatureServicePort, TemperatureService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TemperatureService
     */
    @WebEndpoint(name = "TemperatureServicePort")
    public TemperatureService getTemperatureServicePort(WebServiceFeature... features) {
        return super.getPort(TemperatureServicePort, TemperatureService.class, features);
    }

}
