package hsoa_1;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-04-19T15:38:20.814+02:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "HSOA_1", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "door_statusResult", targetNamespace = "HSOA_1")
    @RequestWrapper(localName = "door_status", targetNamespace = "HSOA_1", className = "hsoa_1.DoorStatus")
    @WebMethod(operationName = "door_status", action = "tns:door_status")
    @ResponseWrapper(localName = "door_statusResponse", targetNamespace = "HSOA_1", className = "hsoa_1.DoorStatusResponse")
    public java.lang.String doorStatus();
}
