package hsoa_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-04-23T20:49:56.675+02:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebServiceClient(name = "Service", 
                  wsdlLocation = "file:/M:/servicemix_equinox/data/pax-web-jsp/DoorService_methods.wsdl",
                  targetNamespace = "HSOA_1") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("HSOA_1", "Service");
    public final static QName ServiceSoap = new QName("HSOA_1", "ServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/M:/servicemix_equinox/data/pax-web-jsp/DoorService_methods.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/M:/servicemix_equinox/data/pax-web-jsp/DoorService_methods.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(ServiceSoap, ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(ServiceSoap, ServiceSoap.class, features);
    }

}
