package net.vandut.agh.magisterka.logic.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-00-13
 * 2012-09-28T00:57:08.058+02:00
 * Generated source version: 2.4.3-fuse-00-13
 * 
 */
@WebService(targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", name = "Logic")
@XmlSeeAlso({ObjectFactory.class})
public interface Logic {

    @WebResult(name = "logic_stopResult", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/")
    @RequestWrapper(localName = "logic_stop", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", className = "net.vandut.agh.magisterka.logic.service.LogicStop")
    @WebMethod(operationName = "logic_stop", action = "tns:logic_stop")
    @ResponseWrapper(localName = "logic_stopRS", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", className = "net.vandut.agh.magisterka.logic.service.LogicStopRS")
    public java.lang.String logicStop();

    @WebResult(name = "logic_statusResult", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/")
    @RequestWrapper(localName = "logic_status", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", className = "net.vandut.agh.magisterka.logic.service.LogicStatus")
    @WebMethod(operationName = "logic_status", action = "tns:logic_status")
    @ResponseWrapper(localName = "logic_statusRS", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", className = "net.vandut.agh.magisterka.logic.service.LogicStatusRS")
    public java.lang.String logicStatus();

    @WebResult(name = "logic_startResult", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/")
    @RequestWrapper(localName = "logic_start", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", className = "net.vandut.agh.magisterka.logic.service.LogicStart")
    @WebMethod(operationName = "logic_start", action = "tns:logic_start")
    @ResponseWrapper(localName = "logic_startRS", targetNamespace = "http://service.logic.magisterka.agh.vandut.net/", className = "net.vandut.agh.magisterka.logic.service.LogicStartRS")
    public java.lang.String logicStart();
}
