package hsoa_1;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-06-04T20:55:26.863+02:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebService(targetNamespace = "HSOA_1", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "get_pressureResult", targetNamespace = "HSOA_1")
    @RequestWrapper(localName = "get_pressure", targetNamespace = "HSOA_1", className = "hsoa_1.GetPressure")
    @WebMethod(operationName = "get_pressure", action = "tns:get_pressure")
    @ResponseWrapper(localName = "get_pressureResponse", targetNamespace = "HSOA_1", className = "hsoa_1.GetPressureResponse")
    public java.lang.String getPressure();

    @WebResult(name = "get_humidityResult", targetNamespace = "HSOA_1")
    @RequestWrapper(localName = "get_humidity", targetNamespace = "HSOA_1", className = "hsoa_1.GetHumidity")
    @WebMethod(operationName = "get_humidity", action = "tns:get_humidity")
    @ResponseWrapper(localName = "get_humidityResponse", targetNamespace = "HSOA_1", className = "hsoa_1.GetHumidityResponse")
    public java.lang.String getHumidity();

    @WebResult(name = "get_temperatureResult", targetNamespace = "HSOA_1")
    @RequestWrapper(localName = "get_temperature", targetNamespace = "HSOA_1", className = "hsoa_1.GetTemperature")
    @WebMethod(operationName = "get_temperature", action = "tns:get_temperature")
    @ResponseWrapper(localName = "get_temperatureResponse", targetNamespace = "HSOA_1", className = "hsoa_1.GetTemperatureResponse")
    public java.lang.String getTemperature();
}
