package hsoa_3;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-06-28T19:48:34.207+02:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebService(targetNamespace = "HSOA_3", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "switch_off4Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_off4", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff4")
    @WebMethod(operationName = "switch_off4", action = "tns:switch_off4")
    @ResponseWrapper(localName = "switch_off4Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff4Response")
    public java.lang.String switchOff4();

    @WebResult(name = "switch_on4Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_on4", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn4")
    @WebMethod(operationName = "switch_on4", action = "tns:switch_on4")
    @ResponseWrapper(localName = "switch_on4Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn4Response")
    public java.lang.String switchOn4();

    @WebResult(name = "switch_off3Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_off3", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff3")
    @WebMethod(operationName = "switch_off3", action = "tns:switch_off3")
    @ResponseWrapper(localName = "switch_off3Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff3Response")
    public java.lang.String switchOff3();

    @WebResult(name = "switch_off1Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_off1", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff1")
    @WebMethod(operationName = "switch_off1", action = "tns:switch_off1")
    @ResponseWrapper(localName = "switch_off1Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff1Response")
    public java.lang.String switchOff1();

    @WebResult(name = "switch_on1Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_on1", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn1")
    @WebMethod(operationName = "switch_on1", action = "tns:switch_on1")
    @ResponseWrapper(localName = "switch_on1Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn1Response")
    public java.lang.String switchOn1();

    @WebResult(name = "switch_statusResult", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_status", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchStatus")
    @WebMethod(operationName = "switch_status", action = "tns:switch_status")
    @ResponseWrapper(localName = "switch_statusResponse", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchStatusResponse")
    public java.lang.String switchStatus();

    @WebResult(name = "switch_on3Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_on3", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn3")
    @WebMethod(operationName = "switch_on3", action = "tns:switch_on3")
    @ResponseWrapper(localName = "switch_on3Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn3Response")
    public java.lang.String switchOn3();

    @WebResult(name = "switch_off2Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_off2", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff2")
    @WebMethod(operationName = "switch_off2", action = "tns:switch_off2")
    @ResponseWrapper(localName = "switch_off2Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOff2Response")
    public java.lang.String switchOff2();

    @WebResult(name = "switch_on2Result", targetNamespace = "HSOA_3")
    @RequestWrapper(localName = "switch_on2", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn2")
    @WebMethod(operationName = "switch_on2", action = "tns:switch_on2")
    @ResponseWrapper(localName = "switch_on2Response", targetNamespace = "HSOA_3", className = "hsoa_3.SwitchOn2Response")
    public java.lang.String switchOn2();
}
