package cam;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * gSOAP 2.8.9 generated service definition
 *
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-06-27T13:26:28.629+02:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebServiceClient(name = "SmartCamera", 
                  wsdlLocation = "file:/M:/servicemix_equinox/data/pax-web-jsp/SmartCamera.wsdl",
                  targetNamespace = "cam") 
public class SmartCamera extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("cam", "SmartCamera");
    public final static QName SmartCamera = new QName("cam", "SmartCamera");
    static {
        URL url = null;
        try {
            url = new URL("file:/M:/servicemix_equinox/data/pax-web-jsp/SmartCamera.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmartCamera.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/M:/servicemix_equinox/data/pax-web-jsp/SmartCamera.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmartCamera(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmartCamera(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmartCamera() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SmartCameraPortType
     */
    @WebEndpoint(name = "SmartCamera")
    public SmartCameraPortType getSmartCamera() {
        return super.getPort(SmartCamera, SmartCameraPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmartCameraPortType
     */
    @WebEndpoint(name = "SmartCamera")
    public SmartCameraPortType getSmartCamera(WebServiceFeature... features) {
        return super.getPort(SmartCamera, SmartCameraPortType.class, features);
    }

}
