package cam;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by FuseSource Services Framework 2.4.3-fuse-01-02
 * 2012-06-27T13:26:28.566+02:00
 * Generated source version: 2.4.3-fuse-01-02
 * 
 */
@WebService(targetNamespace = "cam", name = "SmartCameraPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SmartCameraPortType {

    /**
     * Service definition of function SmartCamera__GetLast
     */
    @WebResult(name = "GetLastReturn", targetNamespace = "")
    @RequestWrapper(localName = "GetLast", targetNamespace = "cam", className = "cam.GetLast")
    @WebMethod(operationName = "GetLast")
    @ResponseWrapper(localName = "GetLastResponse", targetNamespace = "cam", className = "cam.GetLastResponse")
    public java.lang.String getLast();

    /**
     * Service definition of function SmartCamera__StartClassifier
     */
    @WebResult(name = "StartClassifierReturn", targetNamespace = "")
    @RequestWrapper(localName = "StartClassifier", targetNamespace = "cam", className = "cam.StartClassifier")
    @WebMethod(operationName = "StartClassifier")
    @ResponseWrapper(localName = "StartClassifierResponse", targetNamespace = "cam", className = "cam.StartClassifierResponse")
    public java.lang.String startClassifier();
}
